runtime: nodejs20  # Ensure compatibility with your Node.js version
env: standard  # App Engine Standard environment

instance_class: F2  # Adjust as needed for performance

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  - url: /_next/static
    static_dir: .next/static
  - url: /.*
    script: auto