export const ACTIONS = {
  MARKETPLACE: {
    IM_INTERESTED_BUTTON_CLICK: 'MARKETPLACE/IM_INTERESTED_BUTTON_CLICK',
    IM_INTERESTED_FORM:{
      SUBMIT_BUTTON_CLICK: 'MARKETPLACE/IM_INTERESTED_FORM/SUBMIT_BUTTON_CLICK',
    },
    ITEM_CLICK: 'MARKETPLACE/ITEM_CLICK',
    LISTING_LOADED: 'MARKETPLACE/LISTING_LOADED',
  }
}