
export const routes = {
  welcome: '/welcome',
  products: '/products',
  aboutUs: '/about-us',
  gallery: '/gallery',
  client: {
    landingPage: '/succession-plan',
    dashboard: '/succession-client',
    report: '/succession-client/report',
    schedule: '/succession-client/schedule',
    builder: (cardId: string, step: string) =>
      `/succession-client/builder?id=${cardId}&step=${step}`,
  },
  whiteClient: {
    // landingPage: '/succession-plan',
    dashboard: (id: string) => `/white-client?id=${id}`,
    report: '/white-client/report',
    builder: (cardId: string, step: string) =>
      `/white-client/builder?id=${cardId}&step=${step}`,
  },
  confidentialFiles: {
    home: (listingId: string) => `/confidential-files?listingId=${listingId}`,
    file: (sellerId: string, category: string) =>
      `/confidential-files/${category}?${sellerId}`,
  },
  broker: {
    dashboard: '/broker/dashboard',
    intake: '/broker/intake',
    client: (sellerID: string) => `/broker/client/${sellerID}`,
    listingItem: (listingId: string) => `/broker/listings/${listingId}`,
  },
  advisor: {
    dashboard: '/advisor/dashboard',
    intake: '/advisor/intake',
    client: (sellerID: string) => `/advisor/client/${sellerID}`,
    listingItem: (listingId: string) => `/advisor/listings/${listingId}`,
  },
  realEstateBroker: {
    dashboard: '/real-estate-broker/dashboard',
    intake: '/real-estate-broker/intake',
  },
  Broker: {
    signup: (username: string) => `/Broker/${username}`,
  },
  realEstateSeller: {
    dashboard: '/real-estate-seller/dashboard',
    intake: '/real-estate-seller/intake',
    intake2: '/real-estate-seller/intake/2',
    dialogue: '/real-estate-seller/dialogue',
    congratulations: '/real-estate-seller/congratulations',
  },
  seller: {
    dashboard: '/seller/dashboard',
    create: '/seller/create',
    create2: '/seller/create/2',
    dialogue: '/seller/dialogue',
    congratulations: '/seller/congratulations',
    cim: '/seller/cim',
    cimBuilder: {
      intake: '/seller/cim/intake',
      documents: '/seller/cim/documents',
      dialogue: '/seller/cim/dialogue',
      report: '/seller/cim/report',
    },
    listing: `/seller/listing`,
    qvest: `/seller/qvest`,
    interested: `/seller/interested`,
    investmentMemo: `/seller/investment-memo`,
    investorDueDiligence: (id: string) => `/seller/investor-due-diligence/${id}`,
  },
  investment: {
    dashboard: '/investment/dashboard',
    create: '/investment/create',
    create2: '/investment/create/2',
    dialogue: '/investment/dialogue',
    congratulations: '/investment/congratulations',
  },
  eCommerce: {
    dashboard: '/ecommerce',
    products: '/ecommerce/products',
    createProduct: '/ecommerce/products/create',
    productDetails: (slug: string) => `/ecommerce/products/${slug}`,
    ediProduct: (slug: string) => `/ecommerce/products/${slug}/edit`,
    categories: '/ecommerce/categories',
    createCategory: '/ecommerce/categories/create',
    editCategory: (id: string) => `/ecommerce/categories/${id}/edit`,
    orders: '/ecommerce/orders',
    createOrder: '/ecommerce/orders/create',
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: '/ecommerce/reviews',
    shop: '/ecommerce/shop',
    cart: '/ecommerce/cart',
    checkout: '/ecommerce/checkout',
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  intake: {
    products: '/intake/form',
    createIntake: '/intake/form/create',
    productDetails: (slug: string) => `/intake/form/${slug}`,
    ediProduct: (slug: string) => `/intake/form/${slug}/edit`,
  },
  searchAndFilter: {
    realEstate: '/search/real-estate',
    nft: '/search/nft',
    flight: '/search/flight',
    provider: '/search/provider',
  },
  support: {
    dashboard: '/support',
    inbox: '/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/support/snippets',
    createSnippet: '/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/support/templates',
    createTemplate: '/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  chat: {
    dashboard: '/chat',
    inbox: '/chat/inbox',
    inboxItem: (id: string) => `/chat/inbox/${id}`,
  },

  cimplified: {
    list: '/seller/cimplified',
  },
  ddDataRoom: {
    list: '/ddDataRoom',
  },
  buildcim: {
    cardItem: (listingId: string, cardId: string, step: string = 'form') =>
      `/seller/cim-builder?listingId=${listingId}&id=${cardId}&step=${step}`,
  },
  logistics: {
    dashboard: '/logistics',
    shipmentList: '/logistics/shipments',
    customerProfile: '/logistics/customer-profile',
    createShipment: '/logistics/shipments/create',
    editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  appointment: {
    dashboard: '/appointment',
    appointmentList: '/appointment/list',
    SellerSpanCard: (id: string) => `/appointment/card/${id}`,
  },
  buyer: {
    dashboard: '/buyer/dashboard',
    matches: '/buyer/matches',
    intake: {
      products: '/buyer/intake/form',
      createIntake: '/buyer/intake/form/create',
      productDetails: (slug: string) => `/buyer/intake/form/${slug}`,
      ediProduct: (slug: string) => `/buyer/intake/form/${slug}/edit`,
    },
    profile: '/buyer/profile',
    memos: '/buyer/memos',
    cim: (id:string) => `/buyer/cim/${id}`,
    interests: '/buyer/interests',
    story: '/buyer/story',
  },
  provider: {
    dashboard: '/provider',
  },
  providers: {
    listingDetails: (id: string) => `/providers/shipments/${id}`,
  },
  executive: {
    dashboard: '',
  },
  'contact-us': {
    'contact-us': '/contact-us',
  },
  analytics: '/analytics',
  financial: {
    dashboard: '/financial',
  },
  file: {
    dashboard: '/file',
    manager: '/file-manager',
    upload: '/file-manager/upload',
    create: '/file-manager/create',
  },
  pos: {
    index: '/point-of-sale',
  },
  clients: {
    dashboard: '/clients',
    profile: (id: string) => `/clients/profile/${id}`,
  },
  eventCalendar: '/event-calendar',
  invoice: {
    home: '/invoice',
    create: '/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
  },
  widgets: {
    cards: '',
    icons: '',
    charts: '',
    maps: '',
    banners: '',
  },
  tables: {
    basic: '/tables/basic',
    collapsible: '/tables/collapsible',
    enhanced: '/tables/enhanced',
    pagination: '/tables/pagination',
    search: '/tables/search',
    stickyHeader: '/tables/sticky-header',
  },
  multiStep: '/multi-step',
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  emailTemplates: '/email-templates',
  profile: '/profile',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  story: '/story',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp1: '',
    signUp2: '',
    signUp3: '',
    signUp4: '',
    signUp5: '',
    // sign in
    signIn1: '',
    signIn2: '',
    signIn3: '',
    signIn4: '',
    signIn5: '',
    // forgot password
    forgotPassword1: '',
    forgotPassword2: '',
    forgotPassword3: '',
    forgotPassword4: '',
    forgotPassword5: '',
    // OTP
    otp1: '',
    otp2: '',
    otp3: '',
    otp4: '',
    otp5: '',
  },
  forgotPassword: '/forgot-password',
  signIn: '/signin',
  signUp: '/signup',
  verifyEmail: (email: string) => '/verify-email?email=' + email,
  ['business-marketplace']: {
    home: '/business-marketplace',
    item: (id: string) => `/business-marketplace/${id}`,
  },
  marketplace: {
    home: '/marketplace',
    item: (id: string) => `/marketplace/${id}`,
  },
  brokerIntakeForm: (id: string) => `/broker/${id}`,
  // Admin Screens
  rolesPermissions: '/roles-permissions',
  adminSellerSpan: '/roles-permissions/seller-span',
  assistant: '/roles-permissions/assistant',
  'succession-plan': '/roles-permissions/succession-plan',
  'cim-builder': '/roles-permissions/cim-builder',
  cimBuilder: {
    'cim-builder': 'cim-builder',
    report: (listingId: string) => `cim-builder/cim?listingId=${listingId}`,
    editCard: (id: string) => `/roles-permissions/cim-builder/edit/${id}`,
    createCard: '/roles-permissions/cim-builder/add',
  },
  'succession-builder': '/roles-permissions/succession-builder',
  successionBuilder: {
    'succession-builder': 'succession-builder',
    report: (listingId: string) =>
      `succession-builder/succession?listingId=${listingId}`,
    editCard: (id: string) =>
      `/roles-permissions/succession-builder/edit/${id}`,
    createCard: '/roles-permissions/succession-builder/add',
  },
  'succession-builder-lite': '/roles-permissions/succession-builder-lite',
  successionBuilderLite: {
    'succession-builder-lite': 'succession-builder-lite',
    report: (listingId: string) =>
      `succession-builder-lite/succession?listingId=${listingId}`,
    editCard: (id: string) =>
      `/roles-permissions/succession-builder-lite/edit/${id}`,
    createCard: '/roles-permissions/succession-builder-lite/add',
  },
  'investment-builder-lite': '/roles-permissions/investment-builder-lite',
  investmentBuilderLite: {
    'investment-builder-lite': 'investment-builder-lite',
    report: (listingId: string) =>
      `investment-builder-lite/investment?listingId=${listingId}`,
    editCard: (id: string) =>
      `/roles-permissions/investment-builder-lite/edit/${id}`,
    createCard: '/roles-permissions/investment-builder-lite/add',
  },
  whiteLabel: {
    whiteLabel: '/roles-permissions/white-label',
    new: '/roles-permissions/white-label/add-new',
    report: (listingId: string) => `white-label/label?builderId=${listingId}`,
    editCard: (id: string) => `/roles-permissions/white-label/edit/${id}`,
    createCard: (id: string) => `/roles-permissions/white-label/add/${id}`,
  },
  rosetta: (id: string) => `/roles-permissions/assistant/rosetta/${id}`,
  supportCentre: '/roles-permissions/support',
  allUsers: '/roles-permissions/users',
  createCard: '/roles-permissions/seller-span/add',
  editCard: (id: string) => `/roles-permissions/seller-span/edit/${id}`,

  // Admin Agent Screens
  agent: {
    dashboard: '/roles-permissions/agent',
    // create: '/agent/create',
    // create2: '/agent/create/2',
    // dialogue: '/agent/dialogue',
    // congratulations: '/agent/congratulations',
  },
};
